version: '3.7'
services:
    neko_watcher:
        build: ./
        networks: 
            neko_net:
    mail:
        image: bytemark/smtp
        networks: 
            neko_net:
                aliases: 
                    - "mail"

networks: 
    neko_net:
        driver: bridge